
// Dictionary for translations
#let dict = (
  de: (
    invoice: "Rechnung",
    period: "Leistungszeitraum",
    date: "Datum",
    invoice_number: "Rechnungsnummer",
    invoice_due: "Zahlungsziel",
    salutation: "Sehr geehrte Damen und Herren,",
    declaration: "vereinbarungsgemäß berechne ich für meine Leistungen wie folgt:",
    position_name: "Bezeichnung",
    position_amount: "Anzahl",
    position_price: "Price",
    position_net: "Netto",
    vat: "Mehrwertsteuer",
    vat_note: "Es wird gemäß §19 Abs. 1 Umsatzsteuergesetz keine Umsatzsteuer erhoben.",
    subtotal: "Zwischensumme",
    total: "Gesamtsumme",
    payment_instruction: "Zahlbar 14 Tage nach Erhalt per Überweisung unter Angabe der Rechnungsnummer als Verwendungszweck auf das folgende Konto:",
    account_holder: "Kontoinhaber",
    iban: "IBAN",
    bic: "BIC",
    thank_you: "Ich bedanke mich für Ihren Auftrag und freue mich auf die weitere Zusammenarbeit.",
    closing: "Mit freundlichen Grüßen",
    worklog: "Stundenzettel",
    worklog_hours: "Stunden",
    worklog_total_hours: "Gesamtstunden",
    worklog_description: "Beschreibung",
  ),
  en: (
    invoice: "Invoice",
    period: "Performance period",
    date: "Date",
    invoice_number: "Invoice number",
    invoice_due: "Time for payment",
    salutation: "Dear ladies and gentlemen,",
    declaration: "As agreed, I charge for my services as follows:",
    position_name: "Name",
    position_amount: "Amount",
    position_price: "Price",
    position_net: "Net",
    vat: "VAT",
    vat_note: "The tax liability is transferred to the recipient of the service according to § 13b of the German VAT Act (UStG).
The VAT is to be paid by the recipient of the service.",
    subtotal: "Sub-total",
    total: "Total",
    payment_instruction: "Payable 14 days after receipt by bank transfer, stating the invoice number as note to payee, to the following account:",
    account_holder: "Account holder",
    iban: "IBAN",
    bic: "BIC",
    thank_you: "Thank you for your order and I look forward to further cooperation.",
    closing: "Best regards",
    worklog: "Work log",
    worklog_hours: "Hours",
    worklog_total_hours: "Total hours",
    worklog_description: "Description",
  ),
)

// Translate function
#let tr(t) = context { dict.at(text.lang).at(t) }
